### ISSUE TITLE
Error in FOAM By Example 

### ISSUE THREAD

**Issue by m-cheung** [foam-framework/foam2#323] opened 2017-05-09 14:51 UTC
When visiting the FOAM By Example page, an error occurs which is possibly preventing the rest of the examples (below creating an account) from loading. The error has been included below

> VM3603:139 Uncaught (in promise) TypeError: Cannot read property 'accounts' of null
    at Object.putFn (eval at runExemplar (FOAMByExampleRunner.js:181), <anonymous>:139:32)
    at Object.put (Sink.js:161)
    at Object.select (ValueIndex.js:73)
    at Object.select (AATree.js:268)
    at Object.select (AATree.js:266)
    at Object.customExecute (TreeIndex.js:551)
    at Object.execute (Plan.js:92)
    at Object.select (MDAO.js:231)
    at Object.forward [as select] (Proxy.js:208)
    at Object.forward [as select] (Proxy.js:208)

**Comment by mdittmer** [comment] 2017-05-09 14:54
@adamvy this appears to be caused by #301

**Comment by jacksonic** [comment] 2017-05-09 15:12
Fixed by fe8dd9df3adbd73f006c8c4f894118c5276873c7

**Closed as completed by jacksonic** 2017-05-09 15:12 UTC
